version: 2.1
jobs:
  build:
    # pre-built images: https://circleci.com/docs/2.0/circleci-images/
    docker:
      - image: circleci/openjdk:8u252
    steps:
      - checkout
      - run: chmod +x client-generator.sh
      - run: ./client-generator.sh
      - run: cd java/retrofit2/ && mvn clean package
