version: 2.1
workflows:
  version: 2
  main:
    jobs:
      - build:
          docker:
            - image: circleci/openjdk:8u252
          steps:
            - checkout
            - run: chmod +x client-generator.sh
            - run: ./client-generator.sh
            - run: cd java/retrofit2/ && mvn clean package

      - publish-github-release:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/
