version: 2.1

executors:
  job-executor:
    docker:
      - image: circleci/openjdk:8u252

# Defining jobs for building and releasing SDK
jobs:
  build:
    executor: job-executor
    steps:
      - checkout
      - run: chmod +x client-generator.sh
      - run: ./client-generator.sh
      - run: cd java/retrofit2/ && mvn clean package -Dmaven.test.skip=true
      - run: cd ../../
      - persist_to_workspace:
          root: java/retrofit2/
          paths:
            - target/

  publish-github-release:
    docker:
      - image: circleci/golang:1.12
    steps:
      - attach_workspace:
          at: java/retrofit2/
      - run: go get -u github.com/tcnksm/ghr
      - run: ls
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION=1.0.0
            ghr -t "${GITHUB_TOKEN}" -u "${CIRCLE_PROJECT_USERNAME}" -r "${CIRCLE_PROJECT_REPONAME}" -c "${CIRCLE_SHA1}" -delete ${VERSION} target/fineract-client-1.0.jar

# Defining workflows to put build and release together
workflows:
  version: 2
  main:
    jobs:
      - build
      - publish-github-release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/
