version: 2.1
jobs:
  build:
    # pre-built images: https://circleci.com/docs/2.0/circleci-images/
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run:
          name: The First Step
          command: ./client-generator.sh