version: 2.1

executors:
  job-executor:
    docker:
      - image: circleci/openjdk:8u252

# Defining jobs for building and releasing SDK
jobs:
  build:
    executor: job-executor
    steps:
      - run: mkdir -p workspace && cd workspace
      - run: git clone https://github.com/Grandolf49/fineract-client.git
      - run: cd fineract-client
      - run: ls -a && chmod +x client-generator.sh
      - run: ./client-generator.sh
      - run: cd out && mvn clean package -Dmaven.test.skip=true
      - persist_to_workspace:
          root: workspace
          paths:
            - fineract-client

  publish-github-release:
    docker:
      - image: circleci/golang:1.12
    steps:
      - attach_workspace:
          at: workspace
      - run: ls -a
      #- run: go get -u github.com/tcnksm/ghr
      #- run: cd out && ls -a
      #- run:
      #    name: "Publish Release on GitHub"
      #    command: |
      #      VERSION=1.0.0
      #      ghr -t "${GITHUB_TOKEN}" -u "${CIRCLE_PROJECT_USERNAME}" -r "${CIRCLE_PROJECT_REPONAME}" -c "${CIRCLE_SHA1}" -delete ${VERSION} target/fineract-client-1.0.jar

# Defining workflows to put build and release togethcd java/retrofit2/
workflows:
  version: 2
  main:
    jobs:
      - build
      - publish-github-release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/
